spring.application.name=Wigell_Travel_API
server.port=8581

spring.boot.admin.client.url=http://localhost:9090
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

management.server.port=6085
spring.boot.admin.client.instance.management-base-url=http://localhost:6085
management.endpoints.web.exposure.include=info,health
management.info.env.enabled=true

#spring.profiles.active=dev
spring.profiles.active=prod

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

info.app.name=Wigell Travel API
info.app.description=Booking system for trips
info.app.version=1.0.0
info.app.author=Markus E
info.app.course=Java Backend

spring.jackson.serialization.indent_output=true